# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

python_script:

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    language: "it"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.200 # Add the IP address of the proxy server
    - 172.30.33.0/24 # You may also provide the subnet mask
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

recorder:
  purge_keep_days: 30
  auto_repack: true
  exclude:
    domains:
      - automation
      - script
    entities:
      # Exclude any logging of the chosen light.
      #- light.my_light
      # Exclude any logging of this color loop script.
      - light.luce_isaglo
      - light.luce_sala
      - light.luce_vittoria
    event_types:
      # Do not record ANY service calls
      - call_service

# Example filter to include specified domains and exclude specified entities
logbook:
  exclude:
    entities:
      - sensor.date_time
      - sensor.time
      - sensor.internet_time
      - sensor.date_time_utc
      - sensor.time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - remote.smart_tv_pro
      - media_player.smart_tv_pro
      - media_player.android_tv_192_168_41_226

battery_notes:
  enable_autodiscovery: true
  default_battery_low_threshold: 15
  battery_increase_threshold: 25

# OpenWrt
device_tracker:
  - platform: luci
    host: !secret router_ip
    username: !secret router_user
    password: !secret router_pwd
    new_device_defaults:
      track_new_devices: true

# MQTT
mqtt:
  #  binary_sensor:
  #    - name: ArduinoAlarmStatus
  #      state_topic: "arduino01/pin2"
  #      payload_on: "0"
  #      payload_off: "1"
  #    - name: ArduinoAlarmActive
  #      state_topic: "arduino01/pin3"
  #      payload_on: "0"
  #      payload_off: "1"
  alarm_control_panel:
    - name: Allarme
      code: !secret antifurto_code
      state_topic: stat/Alarm
      command_topic: cmnd/Alarm
      payload_arm_home: armed_home
      payload_arm_away: armed_away
      payload_disarm: disarmed
      qos: 2
  sensor: !include openwrt.yaml

sensor:
  - platform: template
    sensors:
      costo_enel_f1:
        friendly_name: "Costo ENEL Fascia 1"
        value_template: "{{ ((states('sensor.pun_fascia_f1')|float(0)) + (0.077|float(0))) | round(2) }}"
        unit_of_measurement: "€/kWh"
        device_class: monetary
        icon_template: mdi:currency-eur
      costo_enel_f2:
        friendly_name: "Costo ENEL Fascia 2"
        value_template: "{{ ((states('sensor.pun_fascia_f2')|float(0)) + (0.077|float(0))) | round(2) }}"
        unit_of_measurement: "€/kWh"
        device_class: monetary
        icon_template: mdi:currency-eur
      costo_enel_f3:
        friendly_name: "Costo ENEL Fascia 3"
        value_template: "{{ ((states('sensor.pun_fascia_f3')|float(0)) + (0.027|float(0))) | round(2) }}"
        unit_of_measurement: "€/kWh"
        device_class: monetary
        icon_template: mdi:currency-eur
      costo_attuale_enel:
        friendly_name: "Costo attuale ENEL"
        value_template: >
          {% if states('sensor.pun_fascia_corrente') == "F1" %}
            {{states('sensor.costo_enel_f1')}}
          {% endif %}
          {% if states('sensor.pun_fascia_corrente') == "F2" %}
            {{states('sensor.costo_enel_f2')}}
          {% endif %}
          {% if states('sensor.pun_fascia_corrente') == "F3" %}
            {{states('sensor.costo_enel_f3')}}
          {% endif %}
        unit_of_measurement: "€/kWh"
        device_class: monetary
        icon_template: mdi:currency-eur
      consumo_enel:
        value_template: "{{ [(states('sensor.enel_power') | int), 0] | max }}"
        unit_of_measurement: "W"
        device_class: power
      temperatura_ingresso:
        friendly_name: "Temperatura ingresso"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.termostato_ingresso', 'current_temperature') }}"
      temperatura_cucina:
        friendly_name: "Temperatura cucina"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.termostato_cucina', 'current_temperature') }}"
      temperatura_sala_2:
        friendly_name: "Temperatura sala zona Finestre"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.termostato_sala_2', 'current_temperature') }}"
      temperatura_sala_tv:
        friendly_name: "Temperatura sala zona TV"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.termostato_sala_tv', 'current_temperature') }}"
      temperatura_corridoio_1p:
        friendly_name: "Temperatura corridoio 1P"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.termostato_corridoio_1p', 'current_temperature') }}"
      temperatura_matrimoniale:
        friendly_name: "Temperatura camera matrimoniale"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.termostato_camera_matrimoniale', 'current_temperature') }}"
      temperatura_sofia:
        friendly_name: "Temperatura camera Sofia"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.termostato_sofia', 'current_temperature') }}"
      temperatura_vittoria:
        friendly_name: "Temperatura camera Vittoria"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.termostato_vittoria', 'current_temperature') }}"
      temperatura_gloisa:
        friendly_name: "Temperatura camera Isabella Gloria"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.termostato_gloisa', 'current_temperature') }}"
      efficienza_pannelli_est:
        friendly_name: "Percentuale efficienza pannelli EST"
        unit_of_measurement: "%"
        value_template: "{{ ((states('sensor.zcs_pv1_power')|float(0)) / (2050|float) * (100|float)) | round(0) }}"
      efficienza_pannelli_sud:
        friendly_name: "Percentuale efficienza pannelli SUD"
        unit_of_measurement: "%"
        value_template: "{{ ((states('sensor.zcs_pv2_power')|float(0)) / (2870|float) * (100|float)) | round(0) }}"
      efficienza_pannelli_media:
        friendly_name: "Percentuale efficienza media pannelli"
        unit_of_measurement: "%"
        value_template: "{{ (((states('sensor.efficienza_pannelli_est')|float(0)) + (states('sensor.efficienza_pannelli_sud')|float(0))) / (2|float)) | round(0) }}"
      in_out_fotovoltaico:
        friendly_name: "Produzione Vendita Fotovoltaico"
        unit_of_measurement: "W"
        value_template: "{{ ((states('sensor.zcs_activepower_pcc_total')|int(0)) * -1) }}"

  - platform: integration
    source: sensor.enel_power
    name: consumo_enel_kwh
    unit_prefix: k
    round: 2

influxdb:
  host: 192.168.42.10
  port: 8086
  database: home
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  measurement_attr: entity_id
  include:
    domains:
      - sensor

shell_command:
  start_pi_camera_video: ssh simone@192.168.41.162 -i /config/.ssh/id_ed25519 'sudo systemctl start remote_camera.service'
  stop_pi_camera_video: ssh simone@192.168.41.162 -i /config/.ssh/id_ed25519 'sudo systemctl stop remote_camera.service'
  stop_nextdns: ssh root@192.168.41.2 -i /data/.ssh/id_ed25519 'nextdns stop'
  start_nextdns: ssh root@192.168.41.2 -i /data/.ssh/id_ed25519 'nextdns start'
  status_nextdns: ssh root@192.168.41.2 -i /data/.ssh/id_ed25519 'nextdns status'

switch:
  - platform: template
    switches:
      alexa_cucina_motion:
        friendly_name: "Alexa cucina motion detection"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.null
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.null
      nextdns_service:
        friendly_name: "Servizio NextDNS"
        turn_on:
          service: script.start_nextdns
          data:
            entity_id: script.start_nextdns
        turn_off:
          service: script.stop_nextdns
          data:
            entity_id: script.stop_nextdns
