# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.200 # Add the IP address of the proxy server
    - 172.30.33.0/24 # You may also provide the subnet mask
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

recorder:
  purge_keep_days: 30
  auto_repack: true
  exclude:
    domains:
      - automation
      - script
    entities:
      # Exclude any logging of the chosen light.
      #- light.my_light
      # Exclude any logging of this color loop script.
      - light.luce_isaglo
      - light.luce_sala
      - light.luce_vittoria
    event_types:
      # Do not record ANY service calls
      - call_service

# Example filter to include specified domains and exclude specified entities
logbook:
  exclude:
    entities:
      - sensor.date_time
      - sensor.time
      - sensor.internet_time
      - sensor.date_time_utc
      - sensor.time_utc
      - sensor.date_time_iso
      - sensor.time_date

# OpenWrt
device_tracker:
  - platform: luci
    host: !secret router_ip
    username: !secret router_user
    password: !secret router_pwd
    new_device_defaults:
      track_new_devices: true

# MQTT
mqtt:
  #  binary_sensor:
  #    - name: ArduinoAlarmStatus
  #      state_topic: "arduino01/pin2"
  #      payload_on: "0"
  #      payload_off: "1"
  #    - name: ArduinoAlarmActive
  #      state_topic: "arduino01/pin3"
  #      payload_on: "0"
  #      payload_off: "1"
  alarm_control_panel:
    - name: Allarme
      code: !secret antifurto_code
      state_topic: stat/Alarm
      command_topic: cmnd/Alarm
      payload_arm_home: armed_home
      payload_arm_away: armed_away
      payload_disarm: disarmed
      qos: 2

sensor:
  - platform: template
    sensors:
      costo_enel_f1:
        friendly_name: "Costo ENEL Fascia 1"
        value_template: "{{ ((states('sensor.pun_fascia_f1')|float) + (0.077|float)) | round(2) }}"
        unit_of_measurement: "€/kWh"
        device_class: monetary
        icon_template: mdi:currency-eur
      costo_enel_f2:
        friendly_name: "Costo ENEL Fascia 2"
        value_template: "{{ ((states('sensor.pun_fascia_f2')|float) + (0.077|float)) | round(2) }}"
        unit_of_measurement: "€/kWh"
        device_class: monetary
        icon_template: mdi:currency-eur
      costo_enel_f3:
        friendly_name: "Costo ENEL Fascia 3"
        value_template: "{{ ((states('sensor.pun_fascia_f3')|float) + (0.027|float)) | round(2) }}"
        unit_of_measurement: "€/kWh"
        device_class: monetary
        icon_template: mdi:currency-eur
      costo_attuale_enel:
        friendly_name: "Costo attuale ENEL"
        value_template: >
          {% if states('sensor.pun_fascia_corrente') == "F1" %}
            {{states('sensor.costo_enel_f1')}}
          {% endif %}
          {% if states('sensor.pun_fascia_corrente') == "F2" %}
            {{states('sensor.costo_enel_f2')}}
          {% endif %}
          {% if states('sensor.pun_fascia_corrente') == "F3" %}
            {{states('sensor.costo_enel_f3')}}
          {% endif %}
        unit_of_measurement: "€/kWh"
        device_class: monetary
        icon_template: mdi:currency-eur
      consumo_enel:
        value_template: "{{ [(states('sensor.enel_power') | int), 0] | max }}"
        unit_of_measurement: "W"
        device_class: energy

  #      sensor.zcs_pv_generation_total:
  #        friendly_name: ZCS PV generation total
  #        unit_of_measurement: Wh
  #        value_template:

  - platform: integration
    source: sensor.enel_power
    name: consumo_enel_kwh
    unit_prefix: k
    round: 2

calendar:
  - platform: caldav
    url: https://caldav.icloud.com
    username: !secret icloud_user
    password: !secret icloud_pwd
    calendars:
      - Family

influxdb:
  host: 192.168.42.10
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  measurement_attr: entity_id
  include:
    domains:
      - sensor
      - binary_sensor

binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: "Google DNS"
    count: 2
    scan_interval: 10

ariston:
  username: !secret remocon_username
  password: !secret remocon_password
  switches:
    - internet_time
    - internet_weather
  sensors:
    - ch_detected_temperature
    - ch_mode
    - ch_comfort_temperature
    - ch_economy_temperature
    #    - ch_gas_last_month
    #    - ch_set_temperature
    - dhw_set_temperature
    - dhw_gas_last_month
    - errors_count
    - mode
    - outside_temperature
    - ch_energy_today
    - dhw_energy_today
    - pressure
    - signal_strength
  binary_sensors:
    - changing_data
    - online
  selector:
    - mode
    - ch_mode
